export const LEDGER_EVENT_TYPES = [
  // "AIRDROP_ACTIVATION",
  // "BOOST_BONUS",
  // "DAILY_REWARDS_AIRDROP",
  // "DAILY_REWARDS_BOOST",
  // "DAILY_REWARDS_LP",
  // "DEPOSIT",
  // "LP_DEPOSIT_FROM_XAMAN",
  // "REWARDS_REDEEMED",
  // "SWIFT_TRANSFER_IN",
  // "SWIFT_TRANSFER_OUT",
  // "WITHDRAWAL",
  // "MANUAL_AIRDROP",
];

