"use client";
import "../../app/herosection.css";
import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";

const FAQSection = () => {
  const [hoveredIndex, setHoveredIndex] = useState(null);

  const faqList = [
    {
      question: "What is BEPVault?",
      answer:
        "BEPVault is a Community Program marketing platform designed to expand USDT liquidity globally. It works as a premier gateway for high-liquidity financial operations.",
    },
    {
      question: "Who can join BEPVault?",
      answer:
        "Anyone, from crypto enthusiasts and influencers to professional marketers and financial experts, can join the Community Program program and start earning.",
    },
    {
      question: "How secure are transactions on BEPVault?",
      answer:
        "All transactions utilize Ripple's blockchain for fast, secure, and transparent processing.",
    },
    {
      question: "What is USDT?",
      answer:
        "USDT is a digital asset created by Ripple Labs to enable fast, low-cost international payments. It's known for its scalability, speed, and integration with financial institutions.",
    },
    {
      question: "Why is USDT ideal for liquidity programs?",
      answer:
        "Its consensus mechanism ensures real-time settlement, minimal fees, and easy integration with existing financial systems—making it ideal for liquidity provisioning.",
    },
    {
      question: "How do Community Programs earn commissions?",
      answer:
        "Community Programs earn commissions based on the volume of transactions or revenue generated by their referrals. The more referrals and transaction volume you bring, the higher your earnings.",
    },

    {
      question: "What are the benefits of joining the BEPVault program?",
      answer:
        "You receive:<ul><li>LP Rewards Upto 0.6%, compounded.</li><li>Performance-based yield tied to real market activity.</li><li>Auto-distributed rewards to your wallet.</li></ul>",
    },
  ];

  return (
    <section className="faq_section section_space" id="faq_section">
      <div className="container">
        <div
          className="ico_heading_block text-center"
          data-aos="fade-up"
          data-aos-duration="800"
        >
          <h2 className="heading_text mb-0">
            Frequently Asked Questions (FAQs)
          </h2>
        </div>

        <div className="ico_accordion" id="accordion_1">
          {faqList.map((faq, index) => (
            <div
              className="accordion-item"
              key={index}
              onMouseEnter={() => setHoveredIndex(index)}
              onMouseLeave={() => setHoveredIndex(null)}
            >
              <div
                className={`icon_arrow ${
                  hoveredIndex === index ? "" : "collapsed"
                }`}
                role="presentation"
              >
                <svg viewBox="0 0 23 27" xmlns="http://www.w3.org/2000/svg">
                  <path d="M10 14.597L10 2.56731C10 1.56579 10.8115 0.753906 11.8125 0.753906C12.8134 0.753906 13.6249 1.56579 13.6249 2.56731L13.6249 14.597C13.6249 15.5985 12.8134 16.4104 11.8125 16.4104C10.8115 16.4104 10 15.5985 10 14.597Z" />
                  <path d="M9.71371 25.8348L1.59744 17.7909C1.49009 17.6845 1.42969 17.5396 1.42969 17.3884L1.42969 14.2693C1.42969 13.7658 2.03695 13.5125 2.39443 13.8668L10.5108 21.9106C10.6181 22.017 10.6785 22.1619 10.6785 22.3131L10.6785 25.4323C10.6785 25.9358 10.0712 26.1891 9.71371 25.8348Z" />
                  <path d="M21.2273 13.8668L13.1111 21.9106C13.0037 22.017 12.9434 22.1619 12.9434 22.3131L12.9434 25.4323C12.9434 25.9358 13.5506 26.1891 13.9081 25.8348L22.0243 17.7909C22.1317 17.6845 22.1921 17.5396 22.1921 17.3884L22.1921 14.2693C22.1921 13.7658 21.5849 13.5125 21.2273 13.8668Z" />
                </svg>
              </div>

              <div
                className={`accordion-button ${
                  hoveredIndex === index ? "" : "collapsed"
                }`}
              >
                {faq.question}
              </div>

              <AnimatePresence initial={false}>
                {hoveredIndex === index && (
                  <motion.div
                    key={`panel_${index}`}
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3, ease: "easeInOut" }}
                    className="accordion-body-wrapper"
                  >
                    <div className="accordion-body">
                      <p
                        dangerouslySetInnerHTML={{ __html: faq.answer }}
                        style={{ marginBottom: 0 }}
                      />
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
